Unleash/unleash-java-sdk

README.md
Also updated URI to the running public demo instance of unleash-server
=> Made example work by adding /features to URI path

README.md, src/main/java/no/finn/unleash/DefaultUnleash.java, src/main/java/no/finn/unleash/metric/ClientMetrics.java, src/main/java/no/finn/unleash/metric/ClientRegistration.java, src/main/java/no/finn/unleash/metric/MetricsBucket.java, src/main/java/no/finn/unleash/metric/ToggleCount.java, src/main/java/no/finn/unleash/metric/UnleashMetricService.java, src/main/java/no/finn/unleash/metric/UnleashMetricServiceImpl.java, src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java, src/main/java/no/finn/unleash/repository/FeatureToggleRepository.java, src/main/java/no/finn/unleash/repository/FeatureToggleResponse.java, src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java, src/main/java/no/finn/unleash/repository/ToggleFetcher.java, src/main/java/no/finn/unleash/util/UnleashConfig.java, src/main/java/no/finn/unleash/util/UnleashScheduledExecutor.java, src/main/java/no/finn/unleash/util/UnleashScheduledExecutorImpl.java, src/main/java/no/finn/unleash/util/UnleashURLs.java, src/test/java/no/finn/unleash/ManualTesting.java, src/test/java/no/finn/unleash/UnleashTest.java, src/test/java/no/finn/unleash/example/UnleashUsageTest.java, src/test/java/no/finn/unleash/metric/UnleashMetricServiceImplTest.java, src/test/java/no/finn/unleash/metric/UnleashMetricsSenderTest.java, src/test/java/no/finn/unleash/repository/FeatureToggleRepositoryTest.java, src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java, src/test/java/no/finn/unleash/util/UnleashConfigTest.java, src/test/java/no/finn/unleash/util/UnleashURLsTest.java
Adds implementation where the client register at startup
and sends metrics to the server regularly.
Needs one more thing:
- An option to disable metrics.
@sveisvei
=> Implement client registration and metrics.

CHANGELOG.md, pom.xml, src/main/java/no/finn/unleash/metric/ClientRegistration.java, src/main/java/no/finn/unleash/util/UnleashConfig.java, src/test/java/no/finn/unleash/util/UnleashConfigTest.java
=> Add sdkVersion to client registration

pom.xml, src/main/java/no/finn/unleash/strategy/StrategyUtils.java, src/test/java/no/finn/unleash/strategy/StrategyUtilsTest.java
This is @ivarconr's PR with some tests added to match the node client.
If these look good then I'll work on the go client next.
Node client PR https://github.com/Unleash/unleash-client-node/pull/54
=> Implement hashing with murmur

CHANGELOG.md, README.md, src/main/java/no/finn/unleash/util/UnleashURLs.java, src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java, src/test/java/no/finn/unleash/util/UnleashURLsTest.java
=> Update API endoint paths for Unleash 3.x

src/main/java/no/finn/unleash/DefaultUnleash.java, src/main/java/no/finn/unleash/repository/FeatureToggleResponse.java, src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java, src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java, src/test/java/no/finn/unleash/util/UnleashConfigTest.java
=> Introduced UNAVAILABLE as possible status in FeatureToggleResponse

pom.xml, src/test/java/no/finn/unleash/FakeUnleashTest.java, src/test/java/no/finn/unleash/UnleashTest.java, src/test/java/no/finn/unleash/example/UnleashUsageTest.java, src/test/java/no/finn/unleash/metric/UnleashMetricServiceImplTest.java, src/test/java/no/finn/unleash/metric/UnleashMetricsSenderTest.java, src/test/java/no/finn/unleash/repository/FeatureToggleRepositoryTest.java, src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java, src/test/java/no/finn/unleash/repository/JsonFeatureToggleParserTest.java, src/test/java/no/finn/unleash/repository/ToggleBackupHandlerFileTest.java, src/test/java/no/finn/unleash/repository/UnleashExceptionExtension.java, src/test/java/no/finn/unleash/strategy/ApplicationHostnameStrategyTest.java, src/test/java/no/finn/unleash/strategy/GradualRolloutRandomStrategyTest.java, src/test/java/no/finn/unleash/strategy/GradualRolloutSessionIdStrategyTest.java, src/test/java/no/finn/unleash/strategy/GradualRolloutUserIdStrategyTest.java, src/test/java/no/finn/unleash/strategy/RemoteAddressStrategyTest.java, src/test/java/no/finn/unleash/strategy/StrategyUtilsTest.java, src/test/java/no/finn/unleash/strategy/StrategyWithContextTest.java, src/test/java/no/finn/unleash/strategy/UserWithIdStrategyTest.java, src/test/java/no/finn/unleash/util/UnleashConfigTest.java, src/test/java/no/finn/unleash/util/UnleashURLsTest.java
=> Upgrade to Junit5

.travis.yml, pom.xml, src/test/java/no/finn/unleash/UnleashTest.java, src/test/java/no/finn/unleash/repository/ToggleBackupHandlerFileTest.java, src/test/resources/log4j2.xml
=> Switch to JaCoCo for coverage

pom.xml, src/main/java/no/finn/unleash/DefaultUnleash.java, src/test/java/no/finn/unleash/UnleashTest.java, src/test/java/no/finn/unleash/integration/ClientSpecificationTest.java, src/test/java/no/finn/unleash/integration/TestCase.java, src/test/java/no/finn/unleash/integration/TestDefinition.java, src/test/java/no/finn/unleash/integration/UnleashContextDefinition.java, src/test/java/no/finn/unleash/repository/FeatureToggleRepositoryTest.java
Implement support for running the specifications defined in https://github.com/Unleash/client-specification
=> Add client-specification tests

src/main/java/no/finn/unleash/repository/FeatureToggleRepository.java, src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java
This PR fixes the issue discussed in #68. 
Previously we're logged also _good_ status codes.
=> Changed logging HTTP status codes

CHANGELOG.md, src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java, src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java
=> fix: Make sure that etag field is never null

README.md, src/main/java/no/finn/unleash/util/UnleashConfig.java, src/test/java/no/finn/unleash/util/UnleashConfigTest.java
I am not sure about all the reflection stuff in the test.
=> feat: Add support for http proxies with basic authentication

CHANGELOG.md, src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java, src/main/java/no/finn/unleash/util/UnleashConfig.java, src/main/java/no/finn/unleash/util/UnleashURLs.java, src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java
This will have no effect until the server is released with support for this, but it's good to be ahead of time :)
=> feat: Add support for filtering toggles on project

src/main/java/no/finn/unleash/metric/ClientMetrics.java, src/main/java/no/finn/unleash/metric/ClientRegistration.java, src/test/java/no/finn/unleash/metric/UnleashMetricServiceImplTest.java
=> fix: Add environment to metrics

src/main/java/no/finn/unleash/strategy/FlexibleRolloutStrategy.java, src/main/java/no/finn/unleash/strategy/GradualRolloutSessionIdStrategy.java, src/main/java/no/finn/unleash/strategy/GradualRolloutUserIdStrategy.java
No functional change here. Just making code easier to read/reason about
=> chore: Use getOrDefault instead of Optional.ofNullable.orElse to aid in readability

pom.xml
There is a critical vulnerabiltiy in Log4j, more information here: https://www.lunasec.io/docs/blog/log4j-zero-day/
=> Fix Log4j vulnerability

.github/workflows/main.yml, .github/workflows/publish_javadoc.yml, .github/workflows/pull_requests.yml, CHANGELOG.md, pom.xml, src/main/java/io/getunleash/Constraint.java, src/main/java/io/getunleash/Operator.java, src/main/java/io/getunleash/UnleashContext.java, src/main/java/io/getunleash/metric/UnleashMetricsSender.java, src/main/java/io/getunleash/strategy/ConstraintUtil.java, src/main/java/io/getunleash/strategy/constraints/ConstraintOperator.java, src/main/java/io/getunleash/strategy/constraints/DateConstraintOperator.java, src/main/java/io/getunleash/strategy/constraints/DateParser.java, src/main/java/io/getunleash/strategy/constraints/NumberConstraintOperator.java, src/main/java/io/getunleash/strategy/constraints/SemanticVersion.java, src/main/java/io/getunleash/strategy/constraints/SemverConstraintOperator.java, src/main/java/io/getunleash/strategy/constraints/StringConstraintOperator.java, src/test/java/io/getunleash/RunOnJavaVersions.java, src/test/java/io/getunleash/RunOnJavaVersionsCondition.java, src/test/java/io/getunleash/integration/ClientSpecificationTest.java, src/test/java/io/getunleash/integration/UnleashContextDefinition.java, src/test/java/io/getunleash/strategy/constraints/DateConstraintOperatorTest.java, src/test/java/io/getunleash/strategy/constraints/NumberConstraintOperatorTest.java, src/test/java/io/getunleash/strategy/constraints/SemanticVersionTest.java, src/test/java/io/getunleash/strategy/constraints/SemverConstraintOperatorTest.java, src/test/java/io/getunleash/strategy/constraints/StringConstraintOperatorTest.java, src/test/java/io/getunleash/util/UnleashConfigTest.java
- Adds String operators, startsWith, endsWith, contains
with support for case insentivity if desired
- Adds Number operators LT, LTE, EQ, GTE, GT for comparing numbers
- Adds Date operators for supporting DATE_AFTER and DATE_BEFORE
- Adds Semver operators for support SEMVER_LT, SEMVER_EQ, SEMVER_GT
=> feat: Add new constraint operators

src/main/java/io/getunleash/DefaultUnleash.java, src/main/java/io/getunleash/repository/FeatureRepository.java, src/main/java/io/getunleash/util/ConstraintMerger.java
Replace all occurrences of io.getunleash.repository.FeatureRepository with io.getunleash.repository.IFeatureRepository
Replace all occurrences of io.getunleash.repository.FeatureRepository with io.getunleash.repository.IFeatureRepository
This makes it easier to inject other implementation (standard or custom) into DefaultUnleash
Closes # . 168
io/getunleash/DefaulttUnleash.java
io/getunleash/util/ConstraintMerger.java
io/getunleash/repository/FeatureRepository
=> Issue #168

pom.xml, src/main/java/io/getunleash/util/UnleashConfig.java
This makes spotless work on Java 17
=> fix: Update spotless plugin

src/main/java/io/getunleash/repository/FeatureRepository.java, src/main/java/io/getunleash/util/ConstraintMerger.java
Proposal to move business logic out of the repository
=> Move the business logic out of the repository

README.md, src/main/java/io/getunleash/metric/DefaultHttpMetricsSender.java, src/main/java/io/getunleash/metric/MetricSender.java, src/main/java/io/getunleash/metric/OkHttpMetricsSender.java, src/main/java/io/getunleash/metric/UnleashMetricServiceImpl.java, src/main/java/io/getunleash/repository/OkHttpFeatureFetcher.java, src/main/java/io/getunleash/util/AtomicLongSerializer.java, src/main/java/io/getunleash/util/DateTimeSerializer.java, src/main/java/io/getunleash/util/MetricSenderFactory.java, src/main/java/io/getunleash/util/OkHttpClientConfigurer.java, src/main/java/io/getunleash/util/UnleashConfig.java, src/test/java/io/getunleash/metric/DefaultHttpMetricsSenderTest.java, src/test/java/io/getunleash/metric/UnleashMetricServiceImplTest.java
So, having added an OkHttpFeatureFetcher in a previous PR, this PR adds a metricssender which uses OkHttp.
=> task: Add an OkHttpMetricsSender

src/main/java/io/getunleash/FakeUnleash.java
Added ability to do `fakeUnleash.enableAllExcept("feature1")` and `fakeUnleash.disableAllExcept("feature1", "feature2")`
https://github.com/Unleash/unleash-client-java/issues/182
=> Added ability to exclude features from enable-/disableAll

README.md
=> fix: customHttpHeader example in README.md

src/main/java/io/getunleash/FakeUnleash.java, src/main/java/io/getunleash/FeatureToggle.java, src/test/java/io/getunleash/DefaultUnleashTest.java, src/test/java/io/getunleash/repository/FeatureToggleRepositoryTest.java, src/test/java/io/getunleash/repository/JsonFeatureToggleParserTest.java, src/test/resources/unleash-repo-v2-with-impression-data.json
This exposes the impression data property on the FeatureToggle class through a getter - `hasImpressionData()` this will default to false if not present
=> feat: expose impression data property

examples/okhttp-example/build.gradle.kts, examples/spring-boot-example/build.gradle.kts
Bump unleash client version to 8.2.0 in both examples
Closes #
=> fix: bump unleash-client-java version in examples

README.md
Hello,
I have added instructions to the README.md for adding the SDK using Gradle, along with the existing Maven (pom.xml) setup. As a developer who primarily uses Gradle, I found it beneficial to include this information for other users who might prefer Gradle over Maven.
This is my first contribution to the Unleash project, and I'm excited to be a part of this community. I hope these additional instructions will help other developers integrate the Unleash SDK more easily.
Updated README.md to include instructions for adding the SDK using Gradle.
=> docs : Add explanation for gradle project

CHANGELOG.md
Adding a note that changelogs have been moved to release notes.
Closes #250
=> chore: add note about the missing versions in changelog

src/test/java/io/getunleash/integration/ClientSpecificationTest.java
This forces the spec tests to just set the state directly on Yggdrasil rather than hoping they'll be hydrated from the API in time (and not overwritten by the backup or bootstrapping)
=> fix: make client spec tests predictably ordered

pom.xml
This version should detect alpine correctly
=> chore: bump yggdrasil

src/main/java/io/getunleash/util/OkHttpClientConfigurer.java, src/main/java/io/getunleash/util/UnleashConfig.java, src/test/java/io/getunleash/metric/DefaultHttpMetricsSenderTest.java, src/test/java/io/getunleash/util/UnleashConfigTest.java
x- headers are deprecated (https://datatracker.ietf.org/doc/html/rfc6648). Let's use unleash- instead.
=> fix: drop x prefix

src/main/java/io/getunleash/util/UnleashConfig.java, src/test/java/io/getunleash/util/UnleashConfigTest.java
Prevent connection id overwrite with custom headers
=> fix: prevent connection overwrite

README.md
The generated docs the [Unleash Client Java SDK documentation](https://docs.getunleash.io/reference/sdks/java) includes a broken link to the migration guide. Since this is automatically generated and displayed in our docs, I'm making the update in this repo so the changes can be reflected in our docs site.
Context: https://unleash-internal.slack.com/archives/C05LUNBS0SZ/p1738938768026249
Closes #
=> fix: Update migration guide link to fix generated docs

.github/workflows/main.yml
=> chore: remove slack notifier from gh-action

src/main/java/io/getunleash/metric/DefaultHttpMetricsSender.java, src/main/java/io/getunleash/metric/OkHttpMetricsSender.java, src/main/java/io/getunleash/repository/HttpFeatureFetcher.java, src/main/java/io/getunleash/repository/OkHttpFeatureFetcher.java, src/main/java/io/getunleash/util/UnleashConfig.java
Just the results of `mvn build`
=> chore: apply formatting

src/main/java/io/getunleash/metric/DefaultHttpMetricsSender.java, src/main/java/io/getunleash/metric/OkHttpMetricsSender.java, src/main/java/io/getunleash/repository/HttpFeatureFetcher.java, src/main/java/io/getunleash/repository/OkHttpFeatureFetcher.java, src/main/java/io/getunleash/repository/YggdrasilAdapters.java, src/main/java/io/getunleash/util/UnleashConfig.java, src/test/java/io/getunleash/DefaultUnleashTest.java, src/test/resources/unleash-repo-v2-advanced.json
Fixes an issue where current time in the context would cause a toggle to evaluate to false if that current time was a non zulu time zone.
=> fix: current time in constraints

src/test/java/io/getunleash/util/UnleashConfigTest.java
add UnleashConfigTest about the case.
apiKey, appName : provided
unleashAPI : not provided
=> chore: add unleash config test
