- README.md
Previous description made me think isEnabled would return the default value if the unleash-server cannot be reached. However, this is not true in the case where the unleash-server has been reached previously and unleash-repo.json exists.
> Updated description of how isEnabled works

- pom.xml
- src/main/java/no/finn/unleash/FakeUnleash.java
- src/test/java/no/finn/unleash/FakeUnleashTest.java
In FakeUnleash, you can't really set a toggle to be disabled, as it just unsets the enabled feature. This meant that unleash.enabled("feature", true) would incorrectly return true for a disabled feature.
> Make FakeUnleash differ "not set" from disabled

- README.md
- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/Unleash.java
- src/main/java/no/finn/unleash/UnleashContext.java
- src/main/java/no/finn/unleash/UnleashContextProvider.java
- src/main/java/no/finn/unleash/strategy/ApplicationHostnameStrategy.java
- src/main/java/no/finn/unleash/strategy/GradualRolloutRandomStrategy.java
- src/main/java/no/finn/unleash/strategy/GradualRolloutSessionIdStrategy.java
- src/main/java/no/finn/unleash/strategy/GradualRolloutUserIdStrategy.java
- src/main/java/no/finn/unleash/strategy/RemoteAddressStrategy.java
- src/main/java/no/finn/unleash/strategy/Strategy.java
- src/main/java/no/finn/unleash/strategy/StrategyUtils.java
- src/main/java/no/finn/unleash/strategy/UserWithIdStrategy.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/test/java/no/finn/unleash/ManualTesting.java
- src/test/java/no/finn/unleash/UnleashTest.java
- src/test/java/no/finn/unleash/strategy/ApplicationHostnameStrategyTest.java
- src/test/java/no/finn/unleash/strategy/GradualRolloutRandomStrategyTest.java
- src/test/java/no/finn/unleash/strategy/GradualRolloutSessionIdStrategyTest.java
- src/test/java/no/finn/unleash/strategy/GradualRolloutUserIdStrategyTest.java
- src/test/java/no/finn/unleash/strategy/RemoteAddressStrategyTest.java
- src/test/java/no/finn/unleash/strategy/StrategyUsingContext.java
- src/test/java/no/finn/unleash/strategy/StrategyWithContextTest.java
- src/test/java/no/finn/unleash/strategy/UserWithIdStrategyTest.java
The idea is to simplify common strategies via a shared unelash context. The context should be possible to provide just in time, or via a request bound probider. 
**Just in time example:**
```java
UnleashContext context = UnleashContext.builder().userId("user@mail.com").build();
unleash.isEnabled("someToggle", unleashContext);
```
The main benefit of just in time is that it is more explicit. It is also makes it easier when ThreadLocal is not bound to the current request. 
**Provider example:**
```java
UnleashContextProvider provider = new CustomUnleashContextProvider();
UnleashConfig config = UnleashConfig.builder().contextProvider(provider);
Unleash unleash = new DefaultUnleash(config):
// context will be provided to the strategy impl via the provided contextProvider. …
```
> Add support for UnleashContext #29

- src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java
- src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/test/java/no/finn/unleash/util/UnleashConfigTest.java
This commit adds a map of custom HTTP headers to UnleashConfig, and
includes these headers in calls to the Unleash server. This may be used
to, e.g., add an `Authorization` field if the server is behind a wrapper
or proxy which requires authentication.
See Unleash/unleash#222 on GitHub for background discussion.
> Add support for custom HTTP headers in API calls

- src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java
- src/main/java/no/finn/unleash/repository/FeatureToggleRepository.java
- src/main/java/no/finn/unleash/repository/ToggleBackupHandlerFile.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutorImpl.java
I cannot use unleash with JDK11 without this change.  So a new release would be nice as well :)
Ref:
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555) ~[log4j-api-2.11.1.jar!/:2.11.1]
at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580) ~[log4j-api-2.11.1.jar!/:2.11.1]
at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567) ~[log4j-api-2.11.1.jar!/:2.11.1]
at no.finn.unleash.util.UnleashScheduledExecutorImpl.<clinit>(UnleashScheduledExecutorImpl.java:9) ~[unleash-client-java-3.1.1.jar!/:3.1.1]
at no.finn.unleash.DefaultUnleash.<clinit>(DefaultUnleash.java:38) ~[unleash-client-java-3.1.1.jar!/:3.1.1]
> LogManager.getLogger() fails runtime with JDK11

- pom.xml
- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/UnleashException.java
- src/main/java/no/finn/unleash/event/EventDispatcher.java
- src/main/java/no/finn/unleash/event/Log4JSubscriber.java
- src/main/java/no/finn/unleash/event/NoOpSubscriber.java
- src/main/java/no/finn/unleash/event/ToggleEvaluated.java
- src/main/java/no/finn/unleash/event/UnleashEvent.java
- src/main/java/no/finn/unleash/event/UnleashReady.java
- src/main/java/no/finn/unleash/event/UnleashSubscriber.java
- src/main/java/no/finn/unleash/metric/ClientMetrics.java
- src/main/java/no/finn/unleash/metric/ClientRegistration.java
- src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java
- src/main/java/no/finn/unleash/repository/FeatureToggleRepository.java
- src/main/java/no/finn/unleash/repository/FeatureToggleResponse.java
- src/main/java/no/finn/unleash/repository/ToggleBackupHandlerFile.java
- src/main/java/no/finn/unleash/repository/ToggleCollection.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutor.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutorImpl.java
- src/test/java/no/finn/unleash/SynchronousTestExecutor.java
- src/test/java/no/finn/unleash/event/SubscriberTest.java
- src/test/java/no/finn/unleash/util/UnleashScheduledExecutorImplTest.java
- subscribe to all or some events by implementing an UnleashSubscriber
- improved support for supplying a custom UnleashScheduledExecutor through UnleashConfig
- default UnleashScheduledExecutor is instantiated lazily
- isolate periodical task from one-off tasks
- adding assert4j for more fluent assertions
- bugfix in FeatureToggleRepository.updateToggles() - do not log error
when status=NOT_CHANGED
targets issue #51
> feat: subscriber api

- src/main/java/no/finn/unleash/metric/MetricsBucket.java
- src/main/java/no/finn/unleash/metric/ToggleCount.java
- src/main/java/no/finn/unleash/metric/UnleashMetricServiceImpl.java
- src/test/java/no/finn/unleash/metric/UnleashMetricServiceImplTest.java
Fixed a couple of issues regarding metrics when
`MetricsBucket.registerCount` is called concurrently
> fix: Thread safety regarding metrics

- pom.xml
This change upgrades the log4j dependency to a version that is not known to have vulnerabilities. A vulnerability (https://www.cvedetails.com/cve/CVE-2017-5645/) has been reported for the previous version.
Fixes #75
> Remove log4j vulnerability

- src/main/java/no/finn/unleash/strategy/RemoteAddressStrategy.java
- src/main/java/no/finn/unleash/util/IpAddressMatcher.java
- src/test/java/no/finn/unleash/strategy/RemoteAddressStrategyTest.java
- src/test/java/no/finn/unleash/util/IpAddressMatcherTest.java
The `IpAddressMatcher` class has been taken from Spring Security 5.1.5.RELEASE (also Apache 2 licensed).
Source: https://github.com/spring-projects/spring-security/blob/5.1.5.RELEASE/web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java
Refs Unleash/unleash-client-node#58
Closes #47
> feat: Add support for IPv6 and CIDR notation in RemoteAddressStrategy

- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/UnleashContext.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/test/java/no/finn/unleash/UnleashContextTest.java
- src/test/java/no/finn/unleash/util/UnleashConfigTest.java
Added support for two new static context fields:
- environment
- appName
These are set in the configuration when the client is
initialised and should be inserted in to the UnleashContext.
This is needed in order to provide support for [Strategy Constraints](https://github.com/Unleash/unleash/issues/442#issuecomment-507168912)
> Add support for static context fields

- CHANGELOG.md
- src/main/java/no/finn/unleash/ActivationStrategy.java
- src/main/java/no/finn/unleash/Constraint.java
- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/Operator.java
- src/main/java/no/finn/unleash/UnleashContext.java
- src/main/java/no/finn/unleash/strategy/ConstraintUtil.java
- src/main/java/no/finn/unleash/strategy/FlexibleRolloutStrategy.java
- src/main/java/no/finn/unleash/strategy/Strategy.java
- src/test/java/no/finn/unleash/UnleashTest.java
- src/test/java/no/finn/unleash/strategy/FlexibleRolloutStrategyTest.java
- src/test/java/no/finn/unleash/strategy/StrategyTest.java
his is an initial implementation of context support. Currently it is guarded behind the "flexibleRollout" strategy. General support for constraints for all strategies will be introduced in v. 4.x.
> feat: add constraint support

- src/main/java/no/finn/unleash/repository/ToggleCollection.java
When implementing an `UnleashSubscriber`, I was attempting to implement a hook for `togglesFetched`.
The argument there is a `FeatureToggleResponse`. That object has a public `getToggleCollection` that returns a `ToggleCollection`.
That object however, is currently useless since it does not expose any get methods, and so my subscriber can't really do anything. 
Since the implementation made sure to return an `unmodifiableCollection`, it seems like an oversight that these methods were not public.
> fix: Make `getFeatures` and `getToggle` public in ToggleCollection

- src/main/java/no/finn/unleash/FeatureToggle.java
java.lang.NullPointerException: null	
at no.finn.unleash.variant.VariantUtil.selectVariant(VariantUtil.java:52) ~[unleash-client-java-3.2.10.jar:3.2.10]
When there are feature toggles with no variants defined if you try to do getVariant from DefaultUnleash. this is because when you do deserializeVersion1 variants is null and not un empty collection.
> Fix java.lang.NullPointerException when no variants defined

- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/FakeUnleash.java
- src/main/java/no/finn/unleash/FallbackAction.java
- src/main/java/no/finn/unleash/Unleash.java
- src/test/java/no/finn/unleash/UnleashTest.java
Today it is possible to define a fallback value which the `isEnabled` will return if the feature toggle is not defined.
We want to also allow the user to send in a fallbackFunction instead of a fallback value (which will take precedence over fallback value).
The fallback function should get to arguments injected: `toggleName` and the enhanced `unleashContext`. The function is implemented by the caller and should return a boolean value. 
Example on how it would work:
`isEnabled("someToggle", context, (toggleName, eContext) -> false)`
> feat: Add support for fallback-action 

- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/Unleash.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutor.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutorImpl.java
- src/test/java/no/finn/unleash/util/UnleashScheduledExecutorImplTest.java
This PR introduces a new `shutdown()` method to 2 interfaces, `Unleash` and `UnleashScheduledExecutor`
In order to properly shutdown a server that's running an Unleash client, all scheduled threads should be shutdown gracefully.
With the current implementation there is no clean way to shutdown the `UnleashScheduledExecutor`. If we're using the default implementation of `UnleashScheduledExecutorImpl`, all fields that would allow us to do so are either private, or are swallowed; The `ScheduledFuture` object returned from `setInterval` is not set to any field in the 2 constructors that call it, `UnleashMetricServiceImpl` and `FeatureToggleRepository`. Nor is the `ScheduledThreadPoolExecutor` exposed (it has a `shutdown()` method).
Our only option right now is to implement our own …
> fix: add `shutdown()` to `Unleash`

- README.md
- src/main/java/no/finn/unleash/CustomHttpHeadersProvider.java
- src/main/java/no/finn/unleash/DefaultCustomHttpHeadersProviderImpl.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/test/java/no/finn/unleash/util/UnleashConfigTest.java
This will make it possible to acquire a new or refresh auth tokens when talking to the server.  This also addresses the following issue.  https://github.com/Unleash/unleash-client-java/issues/94
> fix: add a custom http headers provider for unleash config class

- src/main/java/no/finn/unleash/repository/ToggleCollection.java
I am currently implementing my own `ToggleFetcher` that uses a Scala http4s client for fetching the toggles, and the constructor for `ToggleCollection` not being public is stopping me from doing so. All of the other constructors needed to make a `FeatureToggleResponse` are already public so I presume this was an oversight rather than a deliberate design decision.
> fix: Make ToggleCollection constructor public

- src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java
- src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java
This PR adds the ability to follow redirects (HTTP 301 - 303). To prevent infinite loops this is done only once. This PR fixes #113
> fix: follow redirect once

- CHANGELOG.md
- pom.xml
- src/main/java/no/finn/unleash/event/Log4JSubscriber.java
- src/main/java/no/finn/unleash/event/UnleashSubscriber.java
- src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java
- src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java
- src/main/java/no/finn/unleash/repository/ToggleBackupHandlerFile.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutorImpl.java
- src/test/java/no/finn/unleash/FakeUnleashTest.java
- src/test/java/no/finn/unleash/SynchronousTestExecutor.java
- src/test/java/no/finn/unleash/UnleashContextTest.java
- src/test/java/no/finn/unleash/UnleashTest.java
- src/test/java/no/finn/unleash/event/SubscriberTest.java
- src/test/java/no/finn/unleash/integration/ClientSpecificationTest.java
- src/test/java/no/finn/unleash/metric/UnleashMetricServiceImplTest.java
- src/test/java/no/finn/unleash/metric/UnleashMetricsSenderTest.java
- src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java
- src/test/java/no/finn/unleash/repository/JsonFeatureToggleParserTest.java
- src/test/java/no/finn/unleash/strategy/GradualRolloutSessionIdStrategyTest.java
- src/test/java/no/finn/unleash/strategy/GradualRolloutUserIdStrategyTest.java
- src/test/java/no/finn/unleash/strategy/RemoteAddressStrategyTest.java
- src/test/java/no/finn/unleash/strategy/UserWithIdStrategyTest.java
- src/test/java/no/finn/unleash/util/UnleashConfigTest.java
- src/test/java/no/finn/unleash/util/UnleashURLsTest.java
- src/test/java/no/finn/unleash/variant/VariantUtilTest.java
To simplify bringing your own logging framework to unleash, this switches unleash's dependency to be on slf4j-api, making us compatible with any framework with an implementation of slf4j (Logback, Log4j, Log4j2 etc.)
In addition this PR completes the migration to assertj and junit5; thereby eliminating our dependency on junit4 and hamcrest.
As well as configuring github actions for building and doing some much needed maintenance on dependencies.
> Migrate to Slf4j for logging

- CHANGELOG.md
- src/main/java/no/finn/unleash/DefaultUnleash.java
I created a new custom activation in Unleash and was very confused as to why it wasn't taking place. People familiar with Unleash would have know what was wrong, in that I hadn't created/registered a corresponding strategy.
This PR adds a warning so it is clear in the calling app which toggle/strategy is affected and how they can address it.
> fix: Add logging for when a matching strategy is not found

- CHANGELOG.md
- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/EvaluatedToggle.java
- src/main/java/no/finn/unleash/FakeUnleash.java
- src/main/java/no/finn/unleash/FeatureToggle.java
- src/main/java/no/finn/unleash/MoreOperations.java
- src/main/java/no/finn/unleash/Unleash.java
- src/main/java/no/finn/unleash/UnleashContext.java
- src/main/java/no/finn/unleash/Variant.java
- src/main/java/no/finn/unleash/lang/NonNullApi.java
- src/main/java/no/finn/unleash/lang/NonNullFields.java
- src/main/java/no/finn/unleash/lang/Nullable.java
- src/main/java/no/finn/unleash/metric/MetricsBucket.java
- src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java
- src/main/java/no/finn/unleash/metric/package-info.java
- src/main/java/no/finn/unleash/package-info.java
- src/main/java/no/finn/unleash/repository/JsonToggleCollectionDeserializer.java
- src/main/java/no/finn/unleash/repository/ToggleRepository.java
- src/main/java/no/finn/unleash/repository/package-info.java
- src/main/java/no/finn/unleash/strategy/package-info.java
- src/main/java/no/finn/unleash/util/IpAddressMatcher.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutor.java
- src/main/java/no/finn/unleash/util/UnleashScheduledExecutorImpl.java
- src/main/java/no/finn/unleash/util/package-info.java
- src/main/java/no/finn/unleash/variant/Payload.java
- src/main/java/no/finn/unleash/variant/VariantDefinition.java
- src/main/java/no/finn/unleash/variant/VariantUtil.java
- src/main/java/no/finn/unleash/variant/package-info.java
- src/test/java/no/finn/unleash/DefaultUnleashTest.java
- src/test/java/no/finn/unleash/FakeUnleashTest.java
Addresses #124 
Refined approach with `more` concept for evaluating all toggles as well as counting metrics.
Example usage:
```
@PostMapping("/features")
@ResponseBody
public List<EvaluatedToggle> featureMetrics(@RequestBody List<FeatureUsage> usage){
usage.forEach(toggle -> {
for (int i = 0; i < toggle.count; i++) {
unleash.more().count(toggle.getName(), toggle.isEnabled());
}
});
UnleashContext cont = createContext();
return unleash.more().evaluateAllToggles(cont);
}
```
This returns a json of features, I might refine this response in my service to strip out nulls/empty variants:
```
[
{
"enabled": true,
"name": "feature",
"variant": {
"name": "disabled",
"payload": {
"type": "string",
"value": null
},
"enabled": false
}
},
{
"enabled": false,
"name": "other-feature",
"variant": { …
```
> feat: Add ability to disable metrics via UnleashContext

- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/test/java/no/finn/unleash/DefaultUnleashTest.java
That allows registering a fallback strategy which will support a broader idea of a 'context matching strategy'. I'll create a separate PR for that strategy to keep the PRs focused on each change.
> feat: Add support for fallback strategy

- src/main/java/no/finn/unleash/metric/UnleashMetricsSender.java
- src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/test/java/no/finn/unleash/util/UnleashConfigTest.java
Making it possible to specify a custom proxy to be used only when communicating with unleash backend
> feat(#136): Adding support for custom proxy

- CHANGELOG.md
- src/main/java/no/finn/unleash/DefaultUnleash.java
- src/main/java/no/finn/unleash/repository/HttpToggleFetcher.java
- src/main/java/no/finn/unleash/repository/ToggleBootstrapHandler.java
- src/main/java/no/finn/unleash/util/UnleashConfig.java
- src/main/java/no/finn/unleash/util/UnleashURLs.java
- src/test/java/no/finn/unleash/event/SubscriberTest.java
- src/test/java/no/finn/unleash/repository/HttpToggleFetcherTest.java
- src/test/java/no/finn/unleash/util/UnleashURLsTest.java
Also warn if trying to check for toggles that don't match the prefix to avoid confusion for why it is always disabled.
> Add support for leveraging namePrefix in Java SDK

- pom.xml
- Though we don't distribute log4j on runtime/compile classpath, since
we have it as a test dependency, it's good to clear up confusion and
make sure to use a presumably bugfree version for our test code as
well
> Upgrades log4j2 to 2.16.0

- CHANGELOG.md
- src/main/java/io/getunleash/repository/ToggleBootstrapHandler.java
- src/test/java/io/getunleash/repository/ToggleBootstrapHandlerTest.java
Co-authored-by: Simon Hornby <simon@getunleash.ai>
> fix: make bootstrap not fail when passed invalid json

- pom.xml
I was setting up unleash Java SDK on my local machine and discovered that jackson databind is outdated and has vulnerability in version 2.13.1.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518
Also updated jackson-core and jackson-annotations to match.
Tests ran good and looks stable.
> fix: upgrade jackson databind due to vulnerability

- .github/workflows/main.yml
- .github/workflows/publish_javadoc.yml
- README.md
Hello!
I was going through the readme and noticed that some urls are outdated and branch name was still pointing to the old `master` instead of `main` and updated them. Please see if we can update these if it's fine.
Thanks!
> Fix: Broken urls and branch names in readme

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/FakeUnleash.java
- src/main/java/io/getunleash/MoreOperations.java
- src/test/java/io/getunleash/FakeUnleashTest.java
- src/test/java/io/getunleash/UnleashTest.java
Adds `getFeatureToggleDefinition` to the interface so we don't need to refer to the concrete `DefaultUnleash` when we want to use that method.
The method was initially added in https://github.com/Unleash/unleash-client-java/pull/36
Please let me know if there are any outstanding reasons this method should not be on the interface or if we'd like to expose the functionality in a different way. Thanks
> Add getFeatureToggleDefinition to interface

- src/main/java/io/getunleash/metric/UnleashMetricsSender.java
- src/main/java/io/getunleash/repository/HttpFeatureFetcher.java
- src/main/java/io/getunleash/repository/OkHttpFeatureFetcher.java
- src/main/java/io/getunleash/util/UnleashConfig.java
This PR makes connect and read timeouts for our http requests configurable, previously they've been hardcoded.
fixes: #163
> task: Make http agent timeouts configurable

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/FakeUnleash.java
- src/main/java/io/getunleash/Unleash.java
- src/test/java/io/getunleash/UnleashTest.java
using more semantic java functional interface `BiPredicate` instead of `BiFunction`.
Has potential to break compatibility with previous versions (see [Discussion points](#Discussion-points)), but makes the code more semantic.
Closes #176.
- src/main/java/io/getunleash/Unleash.java
- src/test/java/io/getunleash/UnleashTest.java
This might break some API consumers if they are using directly the interface `BiFunction` instead of a lambda.
> chorus: using more semantic java interface

- src/main/java/io/getunleash/DefaultUnleash.java
- src/test/java/io/getunleash/UnleashTest.java
As a change from earlier, this now increments yes/no as well as which variant was received in the MetricsBucket.
To reflect behaviour of Node SDK from https://github.com/Unleash/unleash-client-node/commit/38f35e658a34c510b4d01f8dd33866ff1119d96e onwards.
> fix: getVariant counts enabled or not

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/FakeUnleash.java
- src/main/java/io/getunleash/Unleash.java
Proposal based on #181:
1. Adds default empty context to avoid having to deal with nulls
2. Transforms `false` into a default fallback action
3. Leaving `boolean isEnabled(String toggleName, UnleashContext context, BiPredicate<String, UnleashContext> fallbackAction)` as the only method that needs to be implemented
> feat: proposal to change default methods in Unleash interface

- README.md
This change attempts to integrate all the information that currently
exists in the [docs.getunleash Java
doc](https://docs.getunleash.io/reference/sdks/java) into the readme.
It also updates some of the links to the doc from the old format to
the new format.
Having multiple versions of the same documentation can be confusing
and cause drift. We're moving to automatically generating the SDK
content on docs.getunleash now (from GitHub readmes), so it's
important to ensure that we don't lose any information in the process.
> docs: merge Java doc with docs.getunleash content

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/event/ImpressionEvent.java
- src/main/java/io/getunleash/event/IsEnabledImpressionEvent.java
- src/main/java/io/getunleash/event/UnleashSubscriber.java
- src/main/java/io/getunleash/event/VariantImpressionEvent.java
- src/test/java/io/getunleash/event/ImpressionDataSubscriberTest.java
Adds two new events "VariantImpressionEvent" and
"IsEnabledImpressionEvent".
Extends UnleashSubscriber with a new impression() method which can be overridden to subscribe to events of super type ImpressionEvent.
The data included in the events match what is documented at
https://docs.getunleash.io/reference/impression-data
> feat: Added impression data events

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/util/UnleashConfig.java
- src/test/java/io/getunleash/DefaultUnleashTest.java
- src/test/java/io/getunleash/util/UnleashConfigTest.java
As mentioned in #206 - The way we did the identifier for a client inadvertently also exposes api keys in the logs when logging that you have more than one client using the same configuration. This fix uses the SHA-256 hash of the three elements (apiKey, appName and instanceId) together and then uses the hex representation of  that as the client identifier instead.
In addition this updates the log message to tell you that you have n clients for appName:instanceId combination.
> fix: Use sha256 digest instead of exposing api key

- .github/workflows/release_to_central.yml
If this works, it would make the workflow the same as we have for Unleash server. 
Trigger the workflow, type the desired version to release and wait.
> task: Added workflow for releasing new versions from GHA

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/strategy/Strategy.java
- src/test/java/io/getunleash/DefaultUnleashTest.java
- src/test/java/io/getunleash/UnleashTest.java
The code selecting an activation strategy was exiting on a first enable match but the strategy being enabled does not mean the feature will be enabled. We need to iterate and evaluate each one of the strategies before returning.
Closes #210
> fix: when using multiple strategies some of them might not be evaluated

- .github/workflows/release_to_central.yml
- .gitignore
- pom.xml
As we saw when we tried to release 8.3.1, we had an `inappropriate ioctl for device`. This PR adds a pinentry rule to loopback, so that we can pass in the passphrase as environment variable. In addition it switches the scm URLs to point to https URLs so our maven process is able to update the github repository with tags. 
Tested in https://github.com/chriswk/javarelease, we know the publishing to maven central repo works, but we need to know that the git tagging works as well.
> feat: make sure gpg entry expects passphrase in environment variable

- pom.xml
- src/main/java/io/getunleash/ActivationStrategy.java
- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/FeatureDependency.java
- src/main/java/io/getunleash/FeatureToggle.java
- src/main/java/io/getunleash/variant/VariantUtil.java
- src/test/java/io/getunleash/DefaultUnleashTest.java
- src/test/java/io/getunleash/DependentFeatureToggleTest.java
- A new feature added in beta to Unleash 5.6. With dependent feature toggle you can configure parent-child relationships. This change makes the SDK evaluate according to the client specifications defined for this.
> feat: Handle dependent feature toggles

- pom.xml
- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/strategy/FlexibleRolloutStrategy.java
- src/main/java/io/getunleash/strategy/GradualRolloutSessionIdStrategy.java
- src/main/java/io/getunleash/strategy/GradualRolloutUserIdStrategy.java
- src/main/java/io/getunleash/strategy/StrategyUtils.java
- src/main/java/io/getunleash/variant/VariantUtil.java
- src/test/java/io/getunleash/DependentFeatureToggleTest.java
- src/test/java/io/getunleash/UnleashTest.java
- src/test/java/io/getunleash/strategy/GradualRolloutSessionIdStrategyTest.java
- src/test/java/io/getunleash/strategy/GradualRolloutUserIdStrategyTest.java
- src/test/java/io/getunleash/strategy/StrategyUtilsTest.java
- src/test/java/io/getunleash/variant/VariantUtilTest.java
Uses a new seed for ensuring a fair distrbution for variants.
After a customer reported that variant distribution seemed skewed we performed some testing and found that since we use the same hash string for both gradual rollout and variant allocation we'd reduced the set of groups we could get to whatever percentage our gradual rollout was set.
Take a gradualRollout of 10%, this will select normalized hashes between 1 and 10, when we then again hash the same string that gave us between 1 and 10, but with modulo 1000 for variants, this will only give us 100 possible groups, instead of the expected 1000.
Force the normalization to accept a seed, and make sure to use a new seed when normalizing the variant distribution hash.
This will require release 9.0.0, since we're changing the signature …
> fix: change seed for variantutils to ensure fair distribution

- src/main/java/io/getunleash/util/Throttler.java
- src/test/java/io/getunleash/util/ThrottlerTest.java
While testing this, we found that successful invocation reduced failure count below 0, this caused the backoff to not work as intended
> fix: prevent failure count going below zero

- src/main/java/io/getunleash/repository/FeatureRepository.java
- src/test/java/io/getunleash/DefaultUnleashTest.java
- src/test/java/io/getunleash/repository/FeatureRepositoryTest.java
On synchronous initialization, we were not failing in case of an invalid response code but still marking the client as ready. With this change, we're making sure we have a valid features collection before marking the client as ready and we're not going to throttle in case of asynchronous initialization.
> chore: allow to fail if unavailable

- src/test/java/io/getunleash/strategy/ApplicationHostnameStrategyTest.java
This removes 3 of the hostname strategy tests that are unlikely to ever work correctly here and probably no longer belong. This logic is now owned by Yggdrasil and has relevant tests covering the behaviour that these 3 tests were previously testing.
Usually not a fan of removing tests to make things work but:
1) These tests now effectively test the underlying library
2) They require setting the hostname env variable. Doing this through Java only the affects JVM, not the Rust code
3) At least one test remains that proves the behaviour works across the FFI boundary (gets the hostname in Java without modification, Rust gets the same hostname later)
> chore: remove 3 hostname tests that are no longer relevant

- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/FakeUnleash.java
- src/main/java/io/getunleash/Unleash.java
- src/main/java/io/getunleash/strategy/Strategy.java
- src/main/java/io/getunleash/variant/VariantUtil.java
- src/test/java/io/getunleash/UnleashTest.java
- src/test/java/io/getunleash/variant/VariantUtilTest.java
Initial PR for setting up a deprecated method that preserves the old hashing algorithm seed
> fix: add deprecated method for old hashing algorithm

- pom.xml
- src/main/java/io/getunleash/strategy/FlexibleRolloutStrategy.java
- src/main/java/io/getunleash/strategy/Strategy.java
- src/main/java/io/getunleash/variant/VariantUtil.java
- src/test/java/io/getunleash/strategy/StrategyVariantTest.java
To make sure the SDK is up to date with our tests. This bumps to the newest client-spec.
> chore: Use client spec 5.1.5 instead of 5.0.2

- src/main/java/io/getunleash/FakeUnleash.java
- src/test/java/io/getunleash/FakeUnleashTest.java
As discussed in #239 - When all is enabled, we had a bit of a surprising
behaviour where we'd fallback to fallback action for
`isEnabled(featureName, fallback)` even if all was enabled and feature
did not exist.
This PR fixes that, and adds tests to confirm this behaviour is intentional.
closes: #239
> fix: enableAll and disableAll overrides fallback

- src/main/java/io/getunleash/DefaultUnleash.java
- src/test/java/io/getunleash/DependentFeatureToggleTest.java
> fix: Always check parent dependency if present

- src/main/java/io/getunleash/UnleashContext.java
- src/test/java/io/getunleash/UnleashContextTest.java
- made builder populate special properties by name
Making the io.getunleash.UnleashContext.Builder populate special properties for convenience. 
Sometimes users may specify a property by name and not by method. Currently this property will not be picked up.
This PR addresses this and picks up the special properties for the convenience of the user.
> UnleashContext.Builder Convenience

- pom.xml
- src/main/java/io/getunleash/DefaultUnleash.java
- src/main/java/io/getunleash/metric/ClientMetrics.java
- src/main/java/io/getunleash/metric/ClientRegistration.java
- src/test/java/io/getunleash/DefaultUnleashTest.java
- src/test/java/io/getunleash/integration/ClientSpecificationTest.java
- src/test/java/io/getunleash/metric/UnleashMetricServiceImplTest.java
- src/test/java/io/getunleash/repository/UnleashEngineStateHandler.java
Bumps Yggdrasil to expose the core version and handle UTF-8 characters
"Fixes" a timing issue on Windows in the tests. How did we not notice that before? Well we've never run these tests on a Windows runner
> chore: update yggdrasil to handle latest spec

- src/main/java/io/getunleash/util/OkHttpClientConfigurer.java
- src/main/java/io/getunleash/util/UnleashConfig.java
- src/test/java/io/getunleash/DefaultUnleashTest.java
- src/test/java/io/getunleash/metric/DefaultHttpMetricsSenderTest.java
- src/test/java/io/getunleash/util/UnleashConfigTest.java
This PR adds client identification headers to the feature and metrics calls that the client makes to Unleash. The headers are:
- `x-unleash-appname`: the name of the application that is using the client. `UNLEASH-APPNAME` will be deleted in another PR (expand/contract pattern)
- `x-unleash-connection-id`: an internal unique identifier for the current instance of the client generated by the built-in UUID lib
- `x-unleash-sdk`: sdk information in the format `unleash-java@<version>` following reference `unleash-lang@<version>` naming pattern
Reference implementation: https://github.com/Unleash/unleash-client-node/pull/690
There's a failing test that I can't reproduce failing locally.
> feat: client identification headers

- src/main/java/io/getunleash/util/UnleashConfig.java
- src/test/java/io/getunleash/util/UnleashConfigTest.java
After some digging I realized that same version setting we use for the new `x-unleash-sdk` is also used for the registration calls. I'm reverting back the `unleash-client-java:version` convention instead of the new `unleash-java@version`. We use the colon convention a lot in the backend code. Since the new header is not used yet it can be synced with the old convention for now.
> fix: revert previous version scheme

- src/main/resources/META-INF/native-image/io.getunleash/unleash-client-java/reflect-config.json
- src/main/resources/META-INF/native-image/io.getunleash/unleash-client-java/resource-config.json
> #267 GraalVM Reachability Metadata

- README.md
- v10_MIGRATION_GUIDE.md
Adds some notes around how to migrate to the upcoming v10 version and what the user should look out for during the migration process
> docs: migration guide

- src/main/java/io/getunleash/repository/ToggleBootstrapProvider.java
Removes a reference to a class that no longer exists
> fix: broken togglebootstraphandler link in javadoc

- pom.xml
Turns out OS resolution doesn't work correctly with transitive dependencies (aka, consumers of the Java SDK). So Yggdrasil can't be correctly resolved. This moves Ygg to a version that has all the binaries packed in so it doesn't need to care
> chore: bump yggdrasil to a version that doesn't need os resolution

- .github/workflows/publish_javadoc.yml
> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04.
> chore: upgrade ubuntu 20.04 which is closing down

- src/main/java/io/getunleash/metric/DefaultHttpMetricsSender.java
- src/main/java/io/getunleash/metric/OkHttpMetricsSender.java
- src/main/java/io/getunleash/repository/HttpFeatureFetcher.java
- src/main/java/io/getunleash/repository/OkHttpFeatureFetcher.java
- src/main/java/io/getunleash/util/OkHttpClientConfigurer.java
- src/main/java/io/getunleash/util/UnleashConfig.java
- src/test/java/io/getunleash/metric/DefaultHttpMetricsSenderTest.java
- src/test/java/io/getunleash/util/UnleashConfigTest.java
Previously same interval was sent to both requests, metrics and features. Now for metrics we are sending metrics interval and for feature fetching, we send refreshInterval.
> fix: different interval headers are now sent for metrics/features

- pom.xml
- src/main/java/io/getunleash/FakeUnleash.java
- src/main/java/io/getunleash/FeatureDefinition.java
- src/main/java/io/getunleash/util/FeatureDefinitionAdapter.java
- src/test/java/io/getunleash/repository/FeatureRepositoryTest.java
- src/test/java/io/getunleash/util/ClientFeaturesParserTest.java
Restores the old `enabled` property on feature defs. I've chosen to rename this to `environmentEnabled`, which I think expresses better what this actually means
> feat: add environmentEnabled property on feature defs

- pom.xml
fixes an issue with loading musl aarch, custom strategies now work for variants, no erroneous logging when using custom strategies
> chore: bump yggdrasil to 0.1.2, 

- src/main/java/io/getunleash/FakeUnleash.java
- src/test/java/io/getunleash/FakeUnleashTest.java
Conditionally enable feature toggles based on matching the context. 
See https://github.com/Unleash/unleash-client-java/issues/266
* FakeUnleash
* FakeUnleashTest
We assume that we will want to define *multiple* conditions concurrently, because that's how unleash works in reality. As a result, `FakeUnleash.conditionallyEnable()` can be called multiple times, and these conditions are ORed together. That way one test can say "enable for x=1" and another says "enable for y=2", and these can co-exist without affecting each other.
We assume that enabling or disabling a feature toggle without specifying a context wipes out any conditionally enabled configurations for the same feature toggles, and vice versa. See the difference between `features` and `conditionalFeatures`
We also assume that we …
> Conditionally enable features based on contexts

- src/main/java/io/getunleash/metric/ClientMetrics.java
- src/main/java/io/getunleash/metric/DefaultHttpMetricsSender.java
- src/test/java/io/getunleash/event/SubscriberTest.java
Seems like the engine can return null when there are no metrics to send. Updated the type signature to say that the bucket is nullable and added an is-not-null check before sending metrics to avoid 400's.
Fixes #301
> fix: add null check before sending metrics

- .github/workflows/pull_requests.yml
- README.md
Drops official support for Java 8
- Notes in docs about supported Java
- Removed Java 8 from build runners for PRs
> docs: java version notes

- pom.xml
Bump gson from `2.11.0` to `2.13.2`
Context for the change: gson in `2.11.0` was tagged as security vulnerability by Sonatype.
> chore: bump gson
